name: CD FastAPI 1
on:
  push:
    branches:
      - 'release/fastapi/v[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.KEI_DOCKER_USERNAME }}
          password: ${{ secrets.KEI_DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: ./back/fastApi/price_predictor
          push: true
          tags: ${{ secrets.KEI_DOCKER_USERNAME }}/robo_fastapi_1:${{ github.sha }}

      - name: Deploy to EC2
        env:
          MAIN_EC2_SSH_KEY: ${{ secrets.MAIN_EC2_SSH_KEY }}
          MAIN_EC2_PUBLIC_IPV4: ${{ secrets.MAIN_EC2_PUBLIC_IPV4 }}
        run: |
          echo "${MAIN_EC2_SSH_KEY}" > /tmp/key.pem
          chmod 600 /tmp/key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ec2-user@${{ env.MAIN_EC2_PUBLIC_IPV4 }} << 'EOF'
          docker pull ${{ secrets.KEI_DOCKER_USERNAME }}/robo_fastapi_1:${{ github.sha }}
          docker stop robo_fastapi_1 || true
          docker rm robo_fastapi_1 || true
          docker run -d \
            --name robo_fastapi_1 \
            -p 8000:8000 \
            ${{ secrets.KEI_DOCKER_USERNAME }}/robo_fastapi_1:${{ github.sha }}
          docker logs robo_fastapi_1
          EOF
